// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1737750156);
user_pref("browser.search.region", "SK");
user_pref("calendar.caldav.googleResync", 1737750155);
user_pref("calendar.list.sortOrder", "6327765a-ed08-4c99-980a-fad33de79179");
user_pref("calendar.registry.6327765a-ed08-4c99-980a-fad33de79179.calendar-main-default", true);
user_pref("calendar.registry.6327765a-ed08-4c99-980a-fad33de79179.calendar-main-in-composite", true);
user_pref("calendar.registry.6327765a-ed08-4c99-980a-fad33de79179.disabled", true);
user_pref("calendar.registry.6327765a-ed08-4c99-980a-fad33de79179.name", "Home");
user_pref("calendar.registry.6327765a-ed08-4c99-980a-fad33de79179.type", "storage");
user_pref("calendar.registry.6327765a-ed08-4c99-980a-fad33de79179.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Prague");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240809151341");
user_pref("extensions.lastAppVersion", "128.1.0");
user_pref("extensions.lastPlatformVersion", "128.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"ce95ede2-0f00-4b53-bdc8-2d7adfc667d6\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ui-rdf.version", 43);
user_pref("mailnews.database.global.datastore.id", "09870e88-f66c-471b-883b-90fca351a02");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.1.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1737835443);
user_pref("toolkit.telemetry.cachedClientID", "19d780d1-9df4-421d-ae6f-0efc9abed007");
user_pref("toolkit.telemetry.previousBuildID", "20240809151341");
